### ISSUE TITLE
Make the Term name changeable

### ISSUE THREAD

**Issue by Yokozuna59** [mrbasel/react-gpa-calculator#1]
Instead of letting the term name be "Term 1" by default:
![defult](https://user-images.githubusercontent.com/87622592/148069850-2ff1d4de-68aa-420c-a6bf-601e8f354aa5.png)

I recommend you to let it be changeable so the user can change it and become more readable, something like this:
![changeable](https://user-images.githubusercontent.com/87622592/148073714-5bc53341-73f3-42df-8fb1-0d5605bd4959.png)

**Comment by mrbasel** [comment]
Thanks for the suggestion. I'll look into it.
